@tool

class_name HarmonimationPlayer
extends AnimationPlayer

## Data from music score, provided to animation widgets
@export var music_data: MusicScoreData:
	# TODO: catch signals from json data changing
	set(val):
		music_data = val
		if is_node_ready():
			apply_animations()

# TODO: add label to indicate current JSON load state
# TODO: add button to force manually re-compute json


# TODO: make parent class for "hrmn animateable nodes"
# TODO: auto-discover mode
## Animation widgets, provided data from music score
@export var widgets: Array[Circle12Notes] = []:
	set(val):
		widgets = val
		if is_node_ready():
			apply_animations()


func _ready() -> void:
	apply_animations()
	# connect JSON change signal to re-apply animations
	music_data.connect("changed", apply_animations)


func apply_animations() -> void:
	print_verbose("apply_animations(): start. music_data=%s, music_data._music_data=%s, music_data._music_data_dict=%s" % [music_data, music_data._music_data, "loaded" if music_data._music_data_dict != null else "null"])
	if music_data == null or music_data._music_data == null:
		printerr("apply_animations(): missing Music Data, cannot animate harmonimation widgets.")
		return
	# refresh any input filename updates first
	# TODO: I think this isn't necessary anymore?
	print_verbose("apply_animations(): checking for score re-parse")
	music_data._manual_ready()

	# create autogenerated Animation on this Player
	print_verbose("apply_animations(): re-creating autogen animation")
	var animation := Utils.setup_animation(self)

	# loop thru all registered widgets
	if widgets == null or widgets.size() == 0:
		printerr("apply_animations(): no widgets to animate")
		return
	print_verbose("apply_animations(): looping thru %d widgets to set animations" % widgets.size())
	for widget in widgets:
		# determine all animations to apply on this widget, and apply them
		for anim in widget.animate_on_data(music_data._music_data_dict):
			Utils.apply_animation(anim, self, animation)
	print("successfully applied music_data to harmonimation widgets!")
	print_verbose("apply_animations(): done")
